SC-8256 Update scanner version
SonarSource/sonarcloud-circleci-orb pull request #23
Opened 2023-08-07 13:45 UTC by ivan-murenko-sonarsource

2023-08-08 23:22 UTC, andredovale requested changes
1. Before running the pipeline, please run locally (with your authorized token):
```
circleci orb pack ./src/main | circleci orb validate -
circleci orb pack ./src/main | circleci orb publish -  sonarsource/sonarcloud@dev:alpha
```

2. Then update the orb version.

2023-08-09 14:33 UTC, andredovale approved these changes

2023-08-09 14:46 UTC, andredovale reviewed
To finish, I think it's necessary to bump the version into `.circleci/config.yml`. Thanks for the effort! 👏🏻

2023-08-09 18:35 UTC, tom-vanbraband-sonarsource approved these changes

2023-08-09 18:38 UTC, merged